# Linear Algebra

## Multiplication

In [3]:
import numpy as np

In [4]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [6]:
u.shape

(4,)

In [7]:
u.shape[0]

4

### Calculate Vector-Vector Multiplication

In [10]:
# Method 1
def vector_vector_multiply(u,v):
    # Pre-requisite: the shape of u and v must be the same
    assert u.shape[0] == v.shape[0]
    
    # Length of u and v
    n = u.shape[0]
    
    result = 0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [11]:
vector_vector_multiply(u,v)

14

In [12]:
# Method2
u.dot(v)

14

## Calculate Matrix-Vector Multiplication

In [13]:
# Two-D has double brackets
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [17]:
# One-D has one bracket
v = np.array([1,0.5,2,1])
v

array([1. , 0.5, 2. , 1. ])

In [18]:
U.shape

(3, 4)

In [19]:
v.shape

(4,)

In [20]:
# Method 1
def matrix_vector_multiply(U,v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiply(U[i], v)
    
    return result

In [21]:
matrix_vector_multiply(U,v)

array([20. ,  6. ,  8.5])

In [22]:
# Method 2
U.dot(v)

array([20. ,  6. ,  8.5])

## Matrix-Matrix Multiplication

In [41]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [42]:
U.shape

(3, 4)

In [43]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [44]:
V.shape

(4, 3)

In [51]:
# Method 1
def matrix_matrix_multiply(U,V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    print(U.shape[0], V.shape[1])
    results = np.zeros((num_rows,num_cols))
    print(results.shape)
    for i in range(num_cols):
        vi = V[:, i]
        print(vi)
        Uvi = matrix_vector_multiply(U,vi)
        print(Uvi)
        results[:,i] = Uvi
    
    return results

In [52]:
matrix_matrix_multiply(U,V)

3 3
(3, 3)
[1. 0. 0. 2.]
[14.  5.  5.]
[1.  0.5 2.  1. ]
[20.   6.   8.5]
[2. 1. 1. 0.]
[13.  5.  9.]


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [55]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [56]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

In [72]:
Vs = V[[1,2,3]]
Vs

array([[0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [70]:
# Inverse Matrix
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 0.33333333, -0.33333333,  0.5       ],
       [-0.66666667,  0.66666667,  0.        ],
       [ 1.33333333, -0.33333333,  0.        ]])

In [71]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])