# Introduction to Numpy

## Import Library

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/gabrielle/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

## Create Arrays

In [3]:
# only take one arg
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6])

In [7]:
a[2]

3

In [8]:
# Replace value in a array
a[2]=10
a

array([ 1,  2, 10,  4,  5,  6])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
# np.linspace(start_num, end_num, size)
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional Array

In [14]:
# Create a two-dimensional array
# np.array((row_nym, col_num))
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
 n=np.array([
     [1,2,3],
     [4,5,6],
     [7,8,9]
 ])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# [rown_num][col_num]
n[0][1]

2

In [19]:
n[0,1]

2

In [20]:
n[0][1]=20

In [21]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
n[2]=[1,1,1]

In [23]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
 n[:,1]

array([20,  5,  1])

## Randomly Genereated Arrays

In [28]:
# Force random to generate the same arrays
np.random.seed(2)
# Generate random array, range: 0-1 (positive numbers)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.seed(2)
# Generate random array (positive or negative numbers)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [32]:
np.random.seed(2)
# Random array, range:0-100, 5 rows and 2 cols
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a + 1

array([1, 2, 3, 4, 5])

In [38]:
a * 2

array([0, 2, 4, 6, 8])

In [50]:
b = np.arange(3,8)
b

array([3, 4, 5, 6, 7])

In [51]:
a + b

array([ 3,  5,  7,  9, 11])

## Comparison Operations

In [54]:
a > b

array([False, False, False, False, False])

In [44]:
a >= 2

array([False, False,  True,  True,  True])

In [55]:
a < b

array([ True,  True,  True,  True,  True])

In [56]:
#list all numbers in b array that are greater than number in a array
b[a < b]

array([3, 4, 5, 6, 7])

## Summarize Operations

In [57]:
a

array([0, 1, 2, 3, 4])

In [58]:
a.min()

0

In [59]:
a.max()

4

In [60]:
a.std()

1.4142135623730951

In [61]:
a.sum()

10